name = "Github project Page"
license = "MIT"
licenselink = "https://github.com/jkawamoto/github-project-landing-page/blob/master/LICENSE.md"
description = "An easy to use landing page theme for github hosted project."
homepage = "https://github.com/jkawamoto/github-project-landing-page"
tags = ["company", "products", "landing page", "opensource"]
features = ["github", "images" ]
min_version= 0.18

[author]
     name = "Junpei Kawamoto"
     homepage = "https://www.jkawamoto.info/"

[original]
    author =  "Omar Abdelhafith"
    homepage = "https://github.com/swiftline/github-project-landing-page"
    repo = "https://github.com/swiftline/github-project-landing-page"
