baseurl = "http://swiftline.github.io"
languageCode = "en-us"
title = "Swiftline"
theme = "github-project-landing-page"

[params]
  SubTitle = "Amazing project."
  Description = """\
    This discription will be used in meta description.\
  """
  AuthorName = "Junpei Kawamoto"
  AuthorURL = "https://www.jkawamoto.info/"
  GithubURL = "https://github.com/jkawamoto/github-project-landing-page"
  ProfilePicture = "img/icon.png"

  GithubRepo = "github-project-landing-page"
  GithubOrg = "jkawamoto"

  googleAnalytics = ""

  first_color="#f8f8f8"
  first_border_color="#e7e7e7"
  first_text_color="#333"

  second_color="white"
  second_text_color="#333"

  header_color="#f8f8f8"
  header_text_color="rgb(51, 51, 51)"

  header_link_color="#777"
  header_link_hover_color="rgb(51, 51, 51)"
